version: "3.8"

services:

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:1.19.6-alpine
    command: ash -c 'until nginx -g "daemon off;"; do sleep 2; done'
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "www:/var/www/"
    depends_on:
      - php

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php/
      args:
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
    volumes:
      - www:/var/www
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - mariadb

  mariadb:
    container_name: ${PROJECT_NAME}_mariadb
    image: mariadb:10.4.13
    volumes:
      - dbData:/var/lib/mysql
      - "./mariadb/conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASS}
    command: --character-set-server=utf8mb4

  maildev:
    container_name: ${PROJECT_NAME}_maildev
    image: djfarrelly/maildev
    command: ["bin/maildev", "--web", "1080", "--smtp", "1025", "--hide-extensions", "STARTTLS"]
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  dbData:
    name: ${PROJECT_NAME}_db
  www:
    name: ${PROJECT_NAME}_www
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../
      o: bind
